### ISSUE TITLE
Snakemake tries to recreate already existing meta files

### ISSUE THREAD

**Issue by DaminK** [michaelschaub/calcium-imaging-analysis#88]
```
WorkflowError:
Error recording metadata for finished job ([WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'D:\\WIPAR\\repo\\.snakemake\\metadata\\tmp_oz_b1nd.cmVzdWx0' -> 'D:\\WIPAR\\repo\\.snakemake\\metadata\\cmVzdWx0cy9HTjA2XzIwMjEtMDEtMjBfMTAtMTUtMTYvYW5hdG9taWNhbC9BbGwvRGVjb2RpbmcvcmZlL2xlZnRfdmlzdWFsLnJpZ2h0X3Zpc3VhbC8wLjA1L21vdXBfdGltZWxhZ3N-MV9tYXhfY29tcG9uZW50c342NC9jaXJjbGVfcGxvdC5wbmc='). Please ensure write permissions for the directory D:\WIPAR\repo\.snakemake
Removing output files of failed job plot_glassbrain since they might be corrupted:
results/GN06_2021-01-20_10-15-16/anatomical/All/Decoding/rfe/left_visual.right_visual/0.05/moup_timelags~1_max_components~64/circle_plot.png, results/GN06_2021-01-20_10-15-16/anatomical/All/Decoding/rfe/left_visual.right_visual/0.05/moup_timelags~1_max_components~64/glassbrain.html
Traceback (most recent call last):
  File "C:\Users\daminkuehn\anaconda3\envs\snakemake\lib\site-packages\snakemake\jobs.py", line 1116, in postprocess
    self.dag.workflow.persistence.finished(
  File "C:\Users\daminkuehn\anaconda3\envs\snakemake\lib\site-packages\snakemake\persistence.py", line 248, in finished
    self._record(
  File "C:\Users\daminkuehn\anaconda3\envs\snakemake\lib\site-packages\snakemake\persistence.py", line 455, in _record
    os.rename(tmpfile.name, recpath)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'D:\\WIPAR\\repo\\.snakemake\\metadata\\tmp_oz_b1nd.cmVzdWx0' -> 'D:\\WIPAR\\repo\\.snakemake\\metadata\\cmVzdWx0cy9HTjA2XzIwMjEtMDEtMjBfMTAtMTUtMTYvYW5hdG9taWNhbC9BbGwvRGVjb2RpbmcvcmZlL2xlZnRfdmlzdWFsLnJpZ2h0X3Zpc3VhbC8wLjA1L21vdXBfdGltZWxhZ3N-MV9tYXhfY29tcG9uZW50c342NC9jaXJjbGVfcGxvdC5wbmc='
```

**Comment by DaminK** [comment]
Issue was solved in snakemake thanks to our bug report! See https://github.com/snakemake/snakemake/issues/1882 for more details
